import { Question } from './types';

export const QUESTIONS: Question[] = [
  {
    id: 'q1',
    type: 'MCQ',
    text: 'Which planet is known as the Red Planet?',
    options: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
    correctAnswer: 'Mars',
  },
  {
    id: 'q2',
    type: 'IMAGE_BASED',
    text: 'Identify the part of the plant responsible for photosynthesis.',
    imageUrl: 'https://images.unsplash.com/photo-1600621946747-df56842d1531?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwbGFudCUyMHBob3Rvc3ludGhlc2lzJTIwZGlhZ3JhbSUyMHNpbXBsZXxlbnwxfHx8fDE3NzAxMTc3MjF8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    options: ['Roots', 'Stem', 'Leaves', 'Flowers'],
    correctAnswer: 'Leaves',
  },
  {
    id: 'q3',
    type: 'INPUT',
    text: 'Calculate the area of a rectangle with length 5cm and width 3cm.',
    placeholder: 'Enter your answer...',
    hint: 'Area = Length × Width',
    correctAnswer: '15',
  },
  {
    id: 'q4',
    type: 'MCQ',
    text: 'What is the capital of France?',
    options: ['London', 'Berlin', 'Madrid', 'Paris'],
    correctAnswer: 'Paris',
  },
  {
    id: 'q5',
    type: 'INPUT',
    text: 'Solve for x: 2x + 4 = 10',
    placeholder: 'x = ?',
    correctAnswer: '3',
  },
  {
    id: 'q6',
    type: 'MCQ',
    text: 'Which animal is a mammal?',
    options: ['Crocodile', 'Penguin', 'Dolphin', 'Shark'],
    correctAnswer: 'Dolphin',
  },
  {
    id: 'q7',
    type: 'IMAGE_BASED',
    text: 'Which geometric shape is shown in the image?',
    imageUrl: 'https://images.unsplash.com/photo-1653945645604-c3f0cb10caf1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnZW9tZXRyaWMlMjBoZXhhZ29uJTIwc2hhcGV8ZW58MXx8fHwxNzcwMTE3NzIwfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    options: ['Triangle', 'Square', 'Pentagon', 'Hexagon'],
    correctAnswer: 'Hexagon',
  },
  {
    id: 'q8',
    type: 'INPUT',
    text: 'Write the past tense of "run".',
    placeholder: 'Type here...',
    correctAnswer: 'ran',
  },
  {
    id: 'q9',
    type: 'MCQ',
    text: 'What is 15% of 200?',
    options: ['20', '25', '30', '35'],
    correctAnswer: '30',
  },
  {
    id: 'q10',
    type: 'MCQ',
    text: 'Who wrote "Romeo and Juliet"?',
    options: ['Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Jane Austen'],
    correctAnswer: 'William Shakespeare',
  },
];
